---
title: "my-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

# Libraries

```{r setup}
library("MOTL")
library("MOFA2")
```


# Read input files

## Parameters

```{r, echo = FALSE}
TL_data_file <- file.path(system.file("extdata/", package = "MOTL"), "TL_data.RDS")
TL_OutDir = system.file("extdata/", package = "MOTL")
```


```{r}
CenterTrg <- FALSE
```


## Learning dataset

Learning dataset directory: 
```{r}
LrnFctrnDir <- system.file("extdata/Lrn_5000D_Fctrzn_100K_001TH", package = "MOTL")
```

Import the learning dataset metadata:
```{r}
expdat_meta_Lrn = readRDS(file.path(LrnFctrnDir,"expdat_meta_Lrn.rds"))
```

Import model:
```{r}
InputModel = file.path(LrnFctrnDir, "Model.hdf5")
Fctrzn = load_model(file = InputModel)
```

Initialize values from factorization:
```{r}
viewsLrn = Fctrzn@data_options$views
likelihoodsLrn = Fctrzn@model_options$likelihoods
MLrn = Fctrzn@dimensions$M
```

```{r}
Fctrzn@expectations[["Tau"]] = Tau_init(viewsLrn, Fctrzn, InputModel)
Fctrzn@expectations[["TauLn"]] = sapply(viewsLrn, TauLn_calculation, likelihoodsLrn, Fctrzn, LrnFctrnDir)
Fctrzn@expectations[["WSq"]] = sapply(viewsLrn, WSq_calculation, Fctrzn, LrnFctrnDir)
Fctrzn@expectations[["W0"]] = sapply(viewsLrn, W0_calculation, CenterTrg, Fctrzn, LrnFctrnDir)
```


## Target dataset

```{r}
expdat_mRNA <- read.table(system.file("extdata/mRNA.csv", package = "MOTL"), sep = ",")
expdat_DNAme <- read.table(system.file("extdata/DNAme.csv", package = "MOTL"), sep = ",")
```


```{r}
expdat_mRNA = mRNA_addVersion(expdat = expdat_mRNA, Lrndat = Fctrzn@expectations$W$mRNA)
```

```{r}
YTrg_list <- list(mRNA = as.matrix(expdat_mRNA), DNAme = as.matrix(expdat_DNAme))
```

```{r}
smpls = colnames(YTrg_list[[1]])
viewsTrg = names(YTrg_list)
views = viewsLrn[is.element(viewsLrn,viewsTrg)]
likelihoods = likelihoodsLrn[views]
```

```{r}
YTrg_list = TargetDataPreparation(views = views, YTrg_list = YTrg_list, 
                                  Fctrzn = Fctrzn, smpls = smpls, expdat_meta_Lrn = expdat_meta_Lrn,
                                  normalization = FALSE, transformation = TRUE)
```

```{r}
TL_param = initTransferLearningParamaters(YTrg = YTrg_list, views = views, 
                                          Fctrzn = Fctrzn, likelihoods = likelihoods)
```

# TRANSFERT LEARNING WITH MOTL

```{r}
ss_start_time = Sys.time()
minFactors = 13 ## floor when dropping factors - number of samples in evaluations
StartDropFactor = 1 # after which iteration to start dropping factors
FreqDropFactor = 1 ## how often to drop factors
StartELBO = 1 #which iteration to start checking ELBO on, excl initiation iteration
FreqELBO = 5 #how often to assess the ELBO
DropFactorTH = 0.01 # factor with lowest max variance, that is less than this, is dropped
MaxIterations = 10000
MinIterations = 2 # as per MOFA with defaults in python, >= 2 (hardcoded floor), exl initial setup
ConvergenceIts = 2 # as per MOFA python defaults
ConvergenceTH = 0.0005 # default for MOFA - fast option
PoisRateCstnt = 0.0001 ## amount to add to the poison rate function to avoid errors
```

```{r, eval = FALSE}
TL_data = transferLearning_function(TL_param = TL_param, MaxIterations = MaxIterations, MinIterations =  MinIterations,
                                    minFactors = minFactors, StartDropFactor = StartDropFactor, 
                                    FreqDropFactor = FreqDropFactor, StartELBO = StartELBO, 
                                    FreqELBO = FreqELBO, DropFactorTH = DropFactorTH,
                                    ConvergenceIts = ConvergenceIts, ConvergenceTH = ConvergenceTH,
                                    CenterTrg = CenterTrg, ss_start_time = ss_start_time, outputDir = TL_OutDir,
                                    views = views, likelihoods = likelihoods, Fctrzn = Fctrzn)
```

```{r echo = FALSE, eval = FALSE}
saveRDS(object = TL_data, file = TL_data_file)
```

```{r echo = FALSE, eval = TRUE}
TL_data <- readRDS(file = TL_data_file)
```



